// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg4DWyfF4206SiT90GP4LRjDsVY8bsvV8',
    appId: '1:420049372283:web:3fc2cefd05bea2f2a44ede',
    messagingSenderId: '420049372283',
    projectId: 'nova-ride-production',
    authDomain: 'nova-ride-production.firebaseapp.com',
    storageBucket: 'nova-ride-production.firebasestorage.app',
    measurementId: 'G-RE28TB2K5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvwJ-AEoWngeU-DTyz3Hfs_J3Ak6x14Tg',
    appId: '1:420049372283:android:37360b8618cbf9c1a44ede',
    messagingSenderId: '420049372283',
    projectId: 'nova-ride-production',
    storageBucket: 'nova-ride-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy2N2pI7z3fkTe3tTRV2vl5qf9cOghrgo',
    appId: '1:420049372283:ios:8f4b7fdb4b6a4bd8a44ede',
    messagingSenderId: '420049372283',
    projectId: 'nova-ride-production',
    storageBucket: 'nova-ride-production.firebasestorage.app',
    iosBundleId: 'com.novaride.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy2N2pI7z3fkTe3tTRV2vl5qf9cOghrgo',
    appId: '1:420049372283:ios:789c49db876a8130a44ede',
    messagingSenderId: '420049372283',
    projectId: 'nova-ride-production',
    storageBucket: 'nova-ride-production.firebasestorage.app',
    iosBundleId: 'com.novaride.rider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg4DWyfF4206SiT90GP4LRjDsVY8bsvV8',
    appId: '1:420049372283:web:965de2e720bb2daea44ede',
    messagingSenderId: '420049372283',
    projectId: 'nova-ride-production',
    authDomain: 'nova-ride-production.firebaseapp.com',
    storageBucket: 'nova-ride-production.firebasestorage.app',
    measurementId: 'G-Y6YNS7P9Q4',
  );
}
